# generated by simpleevo jobs; sourced by job.sh
export ANTHROPIC_API_KEY=sk-lvzbxtlqxgnfjjolcmppbigyjjncpxzlgafjzeydcnipjrth
export ANTHROPIC_AUTH_TOKEN=a707a4003ea449cf834c4e2b0532507f.1jOuUhrvaVxJYNhO
export ANTHROPIC_BASE_URL=https://open.bigmodel.cn/api/anthropic
export HEPAI_API_KEY=sk-SwhoZIEWysEbixCbwNJWFipuEHcarulyFOUfOTsZEQrUDDy
export HTTPS_PROXY=http://192.168.237.165:3128
export HTTP_PROXY=http://192.168.237.165:3128
export NO_PROXY=localhost,127.0.0.1,aiapi.ihep.ac.cn,.ihep.ac.cn,junoeos01.ihep.ac.cn
export OPENAI_API_KEY=sk-lvzbxtlqxgnfjjolcmppbigyjjncpxzlgafjzeydcnipjrth
export PYTHONPATH=/lustrefs/juno26/users/lidian/SimpleEvolution
export http_proxy=http://192.168.237.165:3128
export https_proxy=http://192.168.237.165:3128
export no_proxy=localhost,127.0.0.1,aiapi.ihep.ac.cn,.ihep.ac.cn,junoeos01.ihep.ac.cn
