"""Run-scoped worker environment shared by every launch backend.

A SimpleEvolution worker needs two things it does NOT inherit automatically on
a remote HTCondor execute node:

1. The simpleevo / proposer / experiment packages on ``PYTHONPATH``.  simpleevo
   is typically *not* pip-installed on the cluster; the packages live next to
   the repo and must be exported explicitly (``package_parent()``).
2. The API-key / proxy / SSL env vars the proposer's model layer reads directly
   from ``os.environ`` (HEPAI_API_KEY, OPENAI_API_KEY, ANTHROPIC_*, proxies,
   SSL_CERT_*).  These must never travel inside the condor job ad; they are
   materialized into a run-scoped ``job_env.sh`` (auditable, mode 0600) that
   ``job.sh`` sources.

One source of truth, two transports:

- ``worker_environment()`` -> a full env dict for a *local* subprocess.
- ``write_job_env()`` -> shell export lines for a *condor* job.sh to source.
"""
from __future__ import annotations

import os
import shlex
from pathlib import Path
from typing import Mapping

# Everything a worker reads out of its own process environment.  Keep this in
# sync with proposer/model.py's key lookups and experiment/apptainer.py's
# _FORWARDED_ENV (which forwards the ANTHROPIC_* subset into the container).
_FORWARDED_ENV = frozenset({
    "ANTHROPIC_API_KEY",
    "ANTHROPIC_AUTH_TOKEN",
    "ANTHROPIC_BASE_URL",
    "HEPAI_API_KEY",
    "ZHIPU_API_KEY",
    "ZHIPUAI_API_KEY",
    "OPENAI_API_KEY",
    "HTTP_PROXY",
    "HTTPS_PROXY",
    "NO_PROXY",
    "http_proxy",
    "https_proxy",
    "no_proxy",
    "SSL_CERT_FILE",
    "SSL_CERT_DIR",
})


def package_parent() -> Path:
    """Parent of the simpleevo package — the directory that holds simpleevo/,
    proposer/ and experiment/ (what workers must have on PYTHONPATH)."""
    from simpleevo import __file__ as simpleevo_file

    return Path(simpleevo_file).resolve().parent.parent


def forwarded_env(environ: Mapping[str, str] | None = None) -> dict[str, str]:
    """The whitelisted env vars present in ``environ`` (default: os.environ)."""
    source = os.environ if environ is None else environ
    return {key: source[key] for key in _FORWARDED_ENV if key in source}


def worker_environment(
    environ: Mapping[str, str] | None = None,
) -> dict[str, str]:
    """Full env a local worker subprocess should run with.

    Local subprocesses get an explicit env (Popen ``env=`` replaces the
    inherited environment), so this returns the complete host environment plus
    the package path and forwarded payload env — never a partial dict.
    """
    source = os.environ if environ is None else environ
    env = dict(source)
    pkg = str(package_parent())
    existing = env.get("PYTHONPATH")
    env["PYTHONPATH"] = pkg + (os.pathsep + existing if existing else "")
    env.update(forwarded_env(source))
    return env


def write_job_env(
    path: str | Path,
    environ: Mapping[str, str] | None = None,
) -> Path:
    """Render the forwarded env + PYTHONPATH as ``export`` lines.

    Only the forwarded subset is exported — dumping the submit host's entire
    environment into a job.sh would leak local state onto execute nodes.  The
    file is chmod 0600 because it carries API keys.
    """
    path = Path(path)
    source = os.environ if environ is None else environ
    env = worker_environment(source)
    lines = ["# generated by simpleevo jobs; sourced by job.sh"]
    for key in sorted(env):
        if key == "PYTHONPATH" or key in _FORWARDED_ENV:
            lines.append(f"export {key}={shlex.quote(env[key])}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    path.chmod(0o600)
    return path
